### ISSUE TITLE
sending email to multiple email ID's

### ISSUE THREAD

**Issue by dileepravindran** [gen-smtp/gen_smtp#138]
is there a way  to send email to multiple email id's?

**Comment by Vagabond** [comment]
Do you mean sending more than one email on a single session?

**Comment by dileepravindran** [comment]
sending email to multiple recipients at one go

**Comment by mworrell** [comment]
No, the recipients are at different servers, so you need to send the same email multiple times. You don't need to re-encode the email though, just send it to a different recipient.
