### ISSUE TITLE
Warning with Elixir 1.5.2 and version 0.12.0

### ISSUE THREAD

**Issue by quatermain** [gen-smtp/gen_smtp#143]
Hello,

I got warning with Elixir 1.5.2, version 0.12.0 and
`Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]`

```
src/smtp_util.erl:71: Warning: crypto:rand_uniform/2 is deprecated and will be removed in a future release; use rand:uniform/1
```

**Comment by mworrell** [comment]
This has been resolved in d8ef7285f4dc98203b667124c7183eeda6f74008
