### ISSUE TITLE
Application crashes in the event of no dns record for a hostname

### ISSUE THREAD

**Issue by alanj853** [gen-smtp/gen_smtp#152]
In the smtp_util module, there is a crash occurring on this line: https://github.com/Vagabond/gen_smtp/blob/master/src/smtp_util.erl#L59

It happens when "inet:gethostbyname(Hostname)" returns a value other than the format requested (e.g {error, nxdomain} ).

Is there a reason that this is so rigidly pattern matched? Or could we perhaps have a case statement that handles the event where there is no dns record.

**Comment by Vagabond** [comment]
Yeah, that seems reasonable if you want to submit a patch.
