### ISSUE TITLE
Please, enable travis-ci

### ISSUE THREAD

**Issue by seriyps** [gen-smtp/gen_smtp#158]
We have .travis.yml, but it's not actually connected to travis: https://travis-ci.org/Vagabond/gen_smtp

Can someone, please, enable it? Docs: https://docs.travis-ci.com/user/getting-started/

**Comment by mworrell** [comment]
I will look into this.

**Comment by mworrell** [comment]
@Vagabond I think you need to do this, as I don't seem to have owner permissions on this repo.

**Comment by arjan** [comment]
Fixed. @mworrell and myself are now also official maintainers.
