### ISSUE TITLE
Add sockopts option `ciphers` to enable insecure protocols

### ISSUE THREAD

**Issue by bencode** [gen-smtp/gen_smtp#176]
I use `gen_smtp` (from Elixir) to send mail relay `smtp.exmail.qq.com` with ssl: true
it will throw `handshake_failure` by default

```elixir
{:error, :retries_exceeded,
 {:network_failure, '113.96.200.115',
  {:error,
   {:tls_alert,
    {:handshake_failure,
     'TLS client: In state hello received SERVER ALERT: Fatal - Handshake Failure\n'}}}}}
``` 

this would be resolved by add sockopts `ciphers` which skipped by [SSL_CONNECT_OPTIONS](https://github.com/Vagabond/gen_smtp/blob/master/src/smtp_socket.erl#L46) currently.
Is there some way to pass `ciphers` opts to inner `ssl:connect`  or resolv this issue. 

### Reference Code
```elixir
ciphers = :ssl.cipher_suites(:all)
sockopts = [
  ciphers: ciphers
]
opts = [
  relay: 'smtp.exmail.qq.com',
  username: 'dayu@helijia.com',
  password: xxx,
  ssl: true,
  sockopts: sockopts,
]
res = :gen_smtp_client.send_blocking({
  'dayu@helijia.com', ['bencode@163.com'],
  'Subject: hello dayu\r\nFrom: <dayu@helijia.com> \r\nTo: <bencode@163.com> \r\n\r\nThis is the email body'
}, opts)
```

**Comment by mworrell** [comment]
I see that indeed you can only pass (and overrule) the options defined in `SSL_CONNECT_OPTIONS`. 

Which OTP version is your Elixir using?
Might be that you are using a newer OTP that defaults to "safe" ciphers only and that the `all` option lets you use the _unsafe_ ones as well.

Changing the code to also let you pass the ciphers shouldn't be too hard, just want to understand the problem before changing it.

**Comment by bencode** [comment]
in production sever:

```shell
Erlang/OTP 21 [erts-10.3.5.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir (1.8.1)
```

Now, I referr [hackney_ssl](https://github.com/benoitc/hackney/blob/master/src/hackney_ssl.erl#L77) 
to set `ciphers ` options, because `:ssl.cipher_suites/1` is deprecated, and I don't know how to call
`:ssl.cipher_suites/2` or `:ssl.cipher_suites/3` correctly. 

```elixir
iex(1)> :ssl.cipher_suites(:default, 'tlsv1.2')
** (FunctionClauseError) no function clause matching in :ssl_cipher.suites/1

    The following arguments were given to :ssl_cipher.suites/1:

        # 1
        'tlsv1.2'

    ssl_cipher.erl:276: :ssl_cipher.suites/1
    ssl.erl:987: :ssl.cipher_suites/2
iex(1)>
```

**Comment by mworrell** [comment]
hackney should be an ok resource to refer to.

I have tagged this for the 1.1 for solving. We should add this option as this might happen more often with old smtp servers using insecure algorithms.
