### ISSUE TITLE
0.15 release

### ISSUE THREAD

**Issue by mworrell** [gen-smtp/gen_smtp#185]
To do:

 - [ ] Release procedure?
 - [ ] Release notes?
 - [ ] Tag
 - [ ] Push to hex
 - [ ] Mail erlang-questions

**Comment by seriyps** [comment]
ping

**Comment by mworrell** [comment]
@arjan do you know the release procedure (and other points, see above)?

**Comment by arjan** [comment]
Done.

[this is how you publish the package](https://hex.pm/docs/rebar3_publish)

**Comment by mworrell** [comment]
Thanks @arjan!

https://github.com/gen-smtp/gen_smtp/releases/tag/0.15.0

@seriyps now we can move ahead with the 1.0 / ranch release.

**Comment by mworrell** [comment]
@arjan Indeed, I usually use rebar3 to publish the Zotonic related packages. But I am not an owner, so can't publish :-)

**Comment by seriyps** [comment]
Thsnks, @arjan, @mworrel

пт, 13 сент. 2019 г., 8:59 Marc Worrell <notifications@github.com>:
