### ISSUE TITLE
Use atom keys for mimetuple "parameters"

### ISSUE THREAD

**Issue by seriyps** [gen-smtp/gen_smtp#188]
`mimetuple()` 4th element has fixed set of keys in it's proplist:

https://github.com/gen-smtp/gen_smtp/blob/e4e665ff81d317161a4be5ab3f955ecf05f244cd/src/mimemail.erl#L80-L86

https://github.com/gen-smtp/gen_smtp/blob/e4e665ff81d317161a4be5ab3f955ecf05f244cd/src/mimemail.erl#L298-L312

They are:

- "transfer-encoding"
- "content-type-params"
- "disposition"
- "disposition-params"

But they are represented as binaries, which makes it more difficult to add proper typespecs.
My proposal is to make those keys atoms. Maybe also replace proplist with map? It will be a breaking change, so, maybe we can include it to 1.0 release?

**Comment by mworrell** [comment]
Makes sense, any stricter type checking is welcome. And moving to maps is more future-proof, especially when working with Elixir and newer Erlang projects.

Maybe we could also make some data structures a bit more robust and self-explanatory. Now they are tuples which I personally need to look up every time I start writing fresh gen_smtp code.

For backwards-compatibility, maybe map any binaries to the atoms?

On a related (but different) issue I saw that we refer to the body of an email as a string or binary, shouldn't that be an iolist?

https://github.com/gen-smtp/gen_smtp/blob/e4e665ff81d317161a4be5ab3f955ecf05f244cd/src/gen_smtp_client.erl#L67
