### ISSUE TITLE
How do I print out a response of "send" or turn on logging?

### ISSUE THREAD

**Issue by GildedHonour** [gen-smtp/gen_smtp#189]
This in Elixir:

    gen_smtp_client:send(...)

will return {:ok, #PID<0.504.0>} in Elixir. In Erlang probably the same.  Nothing more.

What I need is a whole output: log or response, in text. For instance, in case of an error I want to be able to see what an error was, a response from a server.

How?

**Comment by mworrell** [comment]
You can use:

```erlang
    gen_smtp_clisnt:send_blocking(Email, Options)
```

This will send the email from within your current process and return the result.

**Comment by GildedHonour** [comment]
That's not what I asked about.

**Comment by seriyps** [comment]
Might it make sense to introduce `send_nonblock` or `send_async` and deprecate `send`? Because it might be quite confusing.

**Comment by seriyps** [comment]
> That's not what I asked about.

Are you sure? `send_blocking` does exactly what you asked: it gives you a response from the server in case of error (as well as success).

Another option is to provide send callback fun: `send(Email, Options, fun(Result) -> io:format("Result: ~p~n", [Result]) end)`

**Comment by mworrell** [comment]
Yes, it might be confusing the the send is by default async.

Maybe (for the 1.0) have:

 * send_async
 * send_sync

I don't think we can change `send` to `send_sync` without breaking almost all depending software.
Though we might want to deprecate `send` and let people change their code to `send_async`.
