### ISSUE TITLE
badmap in mimemail:encode

### ISSUE THREAD

**Issue by heyoka** [gen-smtp/gen_smtp#198]
Hi, first of all thank you for providing this useful library.
According to the spec for mimetuple() this should work:
```
mimemail:encode({<<"text">>, <<"html">>,
      [{<<"Subject">>, Subject},
         {<<"From">>, From},
         {<<"To">>, To}],
      [{<<"Content-Type">>, <<"text/html">>}],
      Body
   }).
```
but I get a badmap error for the headers field, instead this works:

```
mimemail:encode({<<"text">>, <<"html">>,
      [{<<"Subject">>, Subject},
         {<<"From">>, From},
         {<<"To">>, To}],
      #{<<"Content-Type">> => <<"text/html">>}, 
      Body
   }).
```
Am I missing something or is it just that the spec is not up to date ?

**Comment by seriyps** [comment]
It was changed recently:

https://github.com/gen-smtp/gen_smtp/blob/628863f0bfd4439678bf216da5c1f55626ec2a8e/src/mimemail.erl#L80

But spec is updated as well. Maybe you are mixing headers and "parameters"?

**Comment by heyoka** [comment]
oh, my bad, thank you
