### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by mworrell** [gen-smtp/gen_smtp#200]
I think we are ready for the 1.0.0 release.

Any non-breaking issues should be scheduled for 1.1 or a later release.

@arjan Could you look into the release? As you have publish rights on Hex.pm

**Comment by mworrell** [comment]
I see some xref warnings:

```
===> Running cross reference analysis...
===> Warning: smtp_rfc822_parse:return_error/2 is unused local function (Xref)
Warning: gen_smtp_server:ranch_child_spec/6 calls deprecated function ranch:child_spec/6 (Xref)
Warning: gen_smtp_server:ranch_start_listener/6 calls deprecated function ranch:start_listener/6 (Xref)
Warning: gen_smtp_server_session:ranch_handshake/3 calls deprecated function ranch:accept_ack/1 (Xref)
Warning: ranch:accept_ack/1 is deprecated function (Xref)
Warning: ranch:child_spec/6 is deprecated function (Xref)
Warning: ranch:start_listener/6 is deprecated function (Xref)
```

Shall we fix those before release?

**Comment by seriyps** [comment]
Well, `smtp_rfc822_parse:return_error/2 is unused local function (Xref)` should be easy to fix, but `ranch`-related I don't think can be easily fixed as long as we do support Ranch < 1.6

**Comment by seriyps** [comment]
Looking at rebar3 docs https://www.rebar3.org/docs/configuration#section-xref, certain warnings can be suppressed like this:

`{xref_ignores, [Module, {Module, Fun}, {Module, Fun, Arity}]}.`

**Comment by mworrell** [comment]
Just adding a xref_ignore.

What shall we do with the deprecated functions?
Keep them for people who are using an older ranch?

**Comment by mworrell** [comment]
I am ok with the ranch warnings - my impression is that quite some people use an older ranch version.

I will add an issue and schedule it for a 1.2 release.

**Comment by mworrell** [comment]
Re-opening, #201 accidentally closed this issue

**Comment by seriyps** [comment]
> I will add an issue and schedule it for a 1.2 release.

Yep, I think it's a good idea.

**Comment by seriyps** [comment]
^ I mean, I think we should add calls to deprecated ranch functions to the same `xref_ignore` wit ha comment that it will be removed in gen_smtp 1.2

**Comment by mworrell** [comment]
Ping @arjan for the release of 1.0

**Comment by skosch** [comment]
Hey guys, any ETA for the 1.0? [mailman/next](https://github.com/mailman-elixir/mailman/tree/next) is ready when you are :)

**Comment by seriyps** [comment]
I see there is one open ticket in 1.0 milestone https://github.com/gen-smtp/gen_smtp/milestone/2 about updated format of mimetuple. I'm not sure if it have to be handled before 1.0.

I can push 1.0 tag probably, but I don't have hex.pm access

**Comment by skosch** [comment]
That issue looks like it's done – you suggested that swoosh will have to update their inputs to `encode`, and the author reacted with a thumbs up. I think you can push the 1.0 release, perhaps with a note about the format change.

**Comment by seriyps** [comment]
Makes sense. I think I can do bit later today, unless there will be any other objections. But, again, we need to ask someone to push to hex.pm after that

**Comment by seriyps** [comment]
I created a couple of PRs to do a "final cleanup" #218 #219 #220. I'll try to merge them tomorrow and will tag 1.0.0 just after that.

**Comment by skosch** [comment]
Thanks Sergey, I appreciate it!

**Comment by arjan** [comment]
I just released 1.0.0. Thanks to all contributors and @seriyps in particular who pushed this release forward!

**Comment by seriyps** [comment]
Amazing! Thanks!

@arjan  Could you please also push `{vsn,"1.0.0"}` change in `.app.src` (even though it will be backdated after 1.0.0 tag), so we won't forget it next time?

Also, seems docs are not available on hex https://hexdocs.pm/gen_smtp/1.0.0/ . I think you might need to do

```
rebar3 edocs        # generate edocs html
ls doc/             # make sure there is a index.html in "doc/" directory
rebar3 hex docs     # push html to hex
```

**Comment by arjan** [comment]
Ahh yes sorry I had changed the version number but forgot to commit it. Did it now... I will cut 1.0.1 because otherwise people still see 0.15 when they are in fact running 1.0.0.
Docs are also pushed!
