### ISSUE TITLE
Failed to send email

### ISSUE THREAD

**Issue by gabrielrinaldi** [gen-smtp/gen_smtp#203]
Let me preface with I am no SMTP or Erlang expert (code pasted here will be in Elixir), but I am having trouble sending an email using SMTP through HubSpot and would like to know where the problem is. 

I can connect fine and send an email using `openssl s_client -starttls smtp -connect smtp.hubapi.com:587`:
![screenshot](https://user-images.githubusercontent.com/38957/79307641-129d6100-7eac-11ea-93db-31fa32c45702.png)

But when sending using `gen_smtp` and the same settings I get: `authentication rejected {ok,<<"500 5.5.0 Bad Input R6S4yT8pcW5sQjZD3CW61N0 - hssmtp\r\n">>}`.

The command I am using is:
```
# I changed the data so private information would be protected

:gen_smtp_client.send({"valid@email.com", ["another@validemail.com"], "Subject: testing\r\nFrom: Aero <valid@email.com>\r\nTo: Gabriel <another@validemail.com>\r\n\r\nThis is the email body"}, [{:relay, "smtp.hubapi.com"}, {:username, "username@7646732.smtp.hubspot.net"}, {:password, "EFL2V6FvYFasdfMdYTVsVrGXqhdM7CJ"}, {:tls, :always}, {:port, 587}, {:trace_fun, &:io.format/2}, {:allowed_tls_versions, [:"tlsv1.2"]}])
```

This is the output I get:
```
{:ok, #PID<0.1108.0>}
MX records for smtp.hubapi.com are [{10,"54.209.45.72"},
                                    {10,"34.227.136.229"},
                                    {10,"52.54.144.175"}]
connected to 54.209.45.72; banner was  smtp.hubapi.com ESMTP R6S4yT8pcW5sQjZD3CW61N0 - hssmtp

Extensions are [{<<"SIZE">>,<<"15728640">>},
                {<<"ENHANCEDSTATUSCODE">>,true},
                {<<"AUTH=PLAIN">>,<<"LOGIN">>},
                {<<"AUTH">>,<<"PLAIN LOGIN">>},
                {<<"STARTTLS">>,true},
                {<<"8BITMIME">>,true}]
Starting TLS
TLS started
Extensions are [{<<"SIZE">>,<<"15728640">>},
                {<<"ENHANCEDSTATUSCODE">>,true},
                {<<"AUTH=PLAIN">>,<<"LOGIN">>},
                {<<"AUTH">>,<<"PLAIN LOGIN">>},
                {<<"8BITMIME">>,true}]
Auth types: <<"PLAIN LOGIN">>
Fixed types: ["PLAIN","LOGIN"]
available authentication types, in order of preference: ["LOGIN","PLAIN"]
got 334 VXNlcm5hbWU6 R6S4yT8pcW5sQjZD3CW61N0 - hssmtp

authentication rejected {ok,<<"500 5.5.0 Bad Input R6S4yT8pcW5sQjZD3CW61N0 - hssmtp\r\n">>}
Authentication status is false
```

If anyone could please point in the right direction I would be grateful, also if this is on the `gen_smtp` side I am happy to help with any more information required.

**Comment by Hermanverschooten** [comment]
It looks to me like HubSpot is adding a session suffix to each response.

**Comment by mworrell** [comment]
Indeed, we are expecting the first part `334 VXNlcm5hbWU6` (per SMTP specs).

Apparently hssmtp is appending some other methods, which we don't ignore.

Maybe we should change this line:

```erlang
{ok, Prompt} when Prompt == <<"334 VXNlcm5hbWU6\r\n">>; Prompt == <<"334 dXNlcm5hbWU6\r\n">> ->
```

to also accept a prompt like hssmtp gives.

**Comment by gabrielrinaldi** [comment]
@mworrell yeah, that how I got it working locally (`{ok, <<"334 VXNlcm5hbWU6", _Rest/binary>>}`). I pushed a fix to a fork, but I have no idea if that was the right way to fix it.

**Comment by mworrell** [comment]
@gabrielrinaldi Could you check this fix? https://github.com/gen-smtp/gen_smtp/pull/204

**Comment by gabrielrinaldi** [comment]
I am getting an error on `mimemail.erl:706: :mimemail.ensure_content_headers/7` when trying to use your branch. 

If I just copy your changes to my branch (based on 0.15) it works, so I think the fix is good, the issue is probably something else in that branch. 

Thanks for looking into it @mworrell ❤️

**Comment by mworrell** [comment]
Can you file an issue for that other error? Might be a problem in the master, which we would like to fix for the 1.0.

**Comment by mworrell** [comment]
@gabrielrinaldi Did you a complete clean build with the new gen_smtp or just pull of the new one?  Wondering if there was an artifact with an older beam or maybe an older call into the library (we are now using maps instead of lists for some options).

**Comment by mworrell** [comment]
I have also update the 0.x branch with the fix for this hssmtp issue.

**Comment by gabrielrinaldi** [comment]
@mworrell I did a clean install, I did had to override the version of ranch to 1.7.1. I’ll test it more today and report back.

Thanks again for fixing this.
