### ISSUE TITLE
mimemail's encode function can throw an exception but the typespec always returns a binary

### ISSUE THREAD

**Issue by flaviogrossi** [gen-smtp/gen_smtp#214]
Currently the encode/2 typespec is `-spec encode(MimeMail :: mimetuple()) -> binary().`

however, the function can throw an exception when an invalid email header is passed (warning: elixir syntax):

```
iex(10)> :mimemail.encode({"text", "plain", [{"To", "me@example.com>"}, {"From", "you@example.com"}], [], ""}, [])
          
** (MatchError) no match of right hand side value: {:error, {0, :smtp_rfc822_parse, ['syntax error before: ', []]}}
    (gen_smtp 0.15.0) /home/flavio/src/nobackup/swooshtest/deps/gen_smtp/src/mimemail.erl:800: :mimemail.encode_header_value/2
    (gen_smtp 0.15.0) /home/flavio/src/nobackup/swooshtest/deps/gen_smtp/src/mimemail.erl:775: :mimemail.encode_headers/1
    (gen_smtp 0.15.0) /home/flavio/src/nobackup/swooshtest/deps/gen_smtp/src/mimemail.erl:160: :mimemail.encode/2
```

please note the invalid `To` header.

Is this behaviour correct and only the typespec should be updated or should the `parse_rfc822_addresses/1` function in the `smtp_util` module be fixed to never throw an exception?

**Comment by seriyps** [comment]
You can't encode exceptions into typespec, so, not much can be done in that sense. One may add a comment saying which exceptions this function may throw, but in your case the exception thrown is quite generic

**Comment by flaviogrossi** [comment]
i was thinking about `binary() | no_return()` like in the rest of the codebase

**Comment by seriyps** [comment]
Unfortunately, it's not how `no_return()` works. no_return should be used only for functions which never return (they always throw an error or do infinite loops).
I know this is a common mistake and it's not really clear from the docs though.

**Comment by flaviogrossi** [comment]
Oh, okay then. I saw other functions in that module returning `binary() | no_return()` and i thought this one should be updated too.
