### ISSUE TITLE
Error on gen_smtp_server:start(smtp_server_example).

### ISSUE THREAD

**Issue by GeorgiouJohn** [gen-smtp/gen_smtp#215]
Hi, I'm trying to run the gen_smtp_server:start(smtp_server_example) and i got :
[root@stunserver::/root/smtp]>../rebar3/rebar3 shell
===> Verifying dependencies...
===> Compiling gen_smtp
Erlang/OTP 22 [erts-10.7] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]

Eshell V10.7  (abort with ^G)
1> gen_smtp_server:start(smtp_server_example).
** exception error: no match of right hand side value false
     in function  gen_smtp_server:get_ranch_version/0 (/root/smtp/src/gen_smtp_server.erl, line 148)
     in call from gen_smtp_server:convert_options/2 (/root/smtp/src/gen_smtp_server.erl, line 90)
     in call from gen_smtp_server:start/3 (/root/smtp/src/gen_smtp_server.erl, line 52)
Did I make some mistake?
Thanks for your help.

**Comment by seriyps** [comment]
It seems you need to start `ranch` first.

Try this:

```erlang
> application:ensure_all_started(gen_smtp).  % start dependencies, eg, ssl and ranch
> gen_smtp_server:start(smtp_server_example).  % start SMTP server
```

**Comment by GeorgiouJohn** [comment]
Thanks. It's working now.
Eshell V10.7  (abort with ^G)
1> application:ensure_all_started(gen_smtp). 
{ok,[ranch,gen_smtp]}
2> 
2> gen_smtp_server:start(smtp_server_example).
{ok,<0.168.0>}
