### ISSUE TITLE
`allow_bare_newlines` is not boolean

### ISSUE THREAD

**Issue by stephanos** [gen-smtp/gen_smtp#216]
Hello!

I was running into a `451 Bare newline detected` error and followed the documentation to ignore it (ie setting it to `true`):
```
{allow_bare_newlines, true | false | fix | strip}
```
But that wasn't fixing the problem. After reading the source code (took me a little since I'm coming from Elixir), I noticed that the tests were actually using the `ignore` atom.

So I think the README and the [type definition](https://github.com/gen-smtp/gen_smtp/blob/c1fc2461cd0ac17d5b1428a7b669f45fb835c0aa/src/gen_smtp_server_session.erl#L100) might be wrong.

**Comment by seriyps** [comment]
Hi. Yep, indeed, it seems it should be `ignore` instead of `true`. Would you mind opening a PR?

**Comment by stephanos** [comment]
I can do that 👍
