### ISSUE TITLE
multiple gen_smtp_server on same port?

### ISSUE THREAD

**Issue by stephanos** [gen-smtp/gen_smtp#229]
Pardon me if this is a silly question but I think I'm only ever seeing one `gen_smtp_server` process at a time. I was hoping to handle a high volume of emails quickly with gen_smtp - if I could have multiple running at the same time, that'd obviously help.

I'm not very well versed with SMTP so I might not know what I'm asking for here, but how hard would it be to have a pool of `gen_smtp_server`s? My other alternative is to start multiple instances of my app but that seems a little inefficient given Erlang's excellent concurrency model.

Thank you
Stephan

**Comment by seriyps** [comment]
Hi. What version of gen_smtp do you use? If it's older than 1.0, there will be single `gen_smtp_server` process, but it will spawn a new `gen_smtp_server_session` process for each connection.
If you use gen_smtp 1.0+, it uses [ranch](https://github.com/ninenines/ranch) to manage connections and it for sure supports multiple parlllel connections and is very efficient.

**Comment by stephanos** [comment]
That's great! We are indeed still using 0.15.0. Just looked at the 1.0 release notes that mentions ranch. Is it just going to be concurrent out of the box or is there any configuration required?

**Comment by seriyps** [comment]
You do.'t have to upgrade. As I said, both 0.15 and 1.0 are able to serve multiple sessions in parallel by default.

In 0.15 gen_smtp _server process is only responsible for accepting new connections. But then it spawns a new process for each accepted connection. So it's pretty much parallel already

**Comment by stephanos** [comment]
Oh, sorry, I must have misunderstood. I'll observe it further but right now I'm logging the important callbacks in my implementation of `@behaviour :gen_smtp_server_session` and it all seems completely sequential.

Oh, now I wonder if I misconfigured my postfix relay server that sits in front of it to maybe only relay 1 email at a time to it. 

Now at least I know that gen_smtp is not the problem :)

**Comment by seriyps** [comment]
> it all seems completely sequential

In gen_smtp 0.15 you receive the current number of active sessions as 2nd argument of your callback module's `init` function.

You won't get it in 1.0 though, but `ranch:info(SmtpServerName)` https://ninenines.eu/docs/en/ranch/1.7/manual/ranch.info/ can be used instead (`SmtpServerName` is the name you provide as a 1st argument to `gen_smtp_server:start`)
