### ISSUE TITLE
Update ranch dependency past 1.6

### ISSUE THREAD

**Issue by crertel** [gen-smtp/gen_smtp#234]
Hello!

I'm doing a bit of work with `bamboo_smtp` (and I think `swoosh` might have a similar issue) and I'm unable to get my dependencies because it relies on `gen_smtp`, which pins `ranch` at `1.6.2`.

Unfortunately, `plug_cowboy` at 2.0 wants `ranch` at `1.7.1`.

Any ideas if either we can bump the dependency here, or how I might work around it?

**Comment by Shemeikka** [comment]
Hi,

There are two open pull requests related to that problem:
- https://github.com/gen-smtp/gen_smtp/pull/227
- https://github.com/gen-smtp/gen_smtp/pull/221

**Comment by crertel** [comment]
Ah, excellent!

Are those getting merged anytime soon?

**Comment by Shemeikka** [comment]
That I don't know. I hope the fix is merged soon.

Maybe @seriyps knows?

**Comment by michelbieleveld** [comment]
Also interested in the merge running in the same issue with bamboo phoenix.

**Comment by djthread** [comment]
I'd also love to see this so I can drop my explicit `{:ranch, "~> 1.7.1", override: true}` dependency. (Hopefully this will work for now, at least.)

Thank you, all contributors!!

**Comment by arjan** [comment]
Should be fixed in 1.1.0 now.

**Comment by crertel** [comment]
Thank you so much! :)

**Comment by LatitudeAdjustment** [comment]
Many thanks, much appreciated!!
