### ISSUE TITLE
Invalid character in filename on Windows

### ISSUE THREAD

**Issue by ollbx** [gen-smtp/gen_smtp#236]
The colon character (":") in the file "test/fixtures/dkim-rsa-private-encrypted:12345.pem" causes issues in Windows, because Windows uses colon in filenames for alternate data streams. Recent versions of git refuse to clone the repository in Windows.

```
Cloning into 'gen_smtp'...
remote: Enumerating objects: 64, done.
remote: Counting objects: 100% (64/64), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 2656 (delta 35), reused 33 (delta 16), pack-reused 2592
Receiving objects: 100% (2656/2656), 3.70 MiB | 6.11 MiB/s, done.
Resolving deltas: 100% (1793/1793), done.
error: invalid path 'test/fixtures/dkim-rsa-private-encrypted:12345.pem'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

I would suggest renaming the file, to fix the issue.

**Comment by fulc927** [comment]
Hello, there I am seconding that, that is not very handy when you have to build from an erlang machine:

error: invalid path 'test/fixtures/dkim-rsa-private-encrypted:12345.pem'

Thank you to take that into consideration please
