### ISSUE TITLE
Low level API

### ISSUE THREAD

**Issue by superbobry** [gen-smtp/gen_smtp#24]
Is it possible to export a set of low-level functions in `gen_smtp_client`, so I can do something like:

``` erlang
{ok, Socket, _Host, _Banner} = gen_smtp_client:connect(...)
{ok, _} = gen_smtp_client:ehlo(...),
ok = gen_stmp_client:auth(...)
```

**Comment by mworrell** [comment]
At the moment this is not planned. If there is a good use case then we could reconsider.
