### ISSUE TITLE
Any Dependencies?

### ISSUE THREAD

**Issue by chapani** [gen-smtp/gen_smtp#26]
Hi,

Thanks for an awesome tool!

Few months ago, I wanted to send email from my erlang app. I installed different smtp servers like postfix but wasn't able to send email ('coz it was too complicated for me). After a while I came across gen_smtp and it worked.

Yesterday, I reinstalled my Ubuntu. After that I tried to send email but it didn't work.  That made me think maybe gen_smtp had dependencies that should be installed before using it. Because, last time I had installed bunch of smtp tools before gen_smtp.

Does gen_smtp have any dependencies? Should my Ubuntu be tuned before using gen_smtp?

Thanks again,
-- buriwoy

**Comment by amadupu** [comment]
i running the following client command to send a self gmail to account test, from an ubuntu vm (network adapter operating in NAT mode)

gen_smtp_client:send({"test@gmail.com", ["test@gmail.com"], unicode:characters_to_binary("Subject: testing\r\nFrom: test@gmail.com \r\nTo: test@gmail.com \r\n\r\nThis is the Test email body")}, [{relay, "smtp.gmail.com"},{ssl, true},{username, "test@gmail.com"}, {password, "testpassword"}]).

however im getting the follwoing exception..(with and without ssl enabled)
{ok,<0.54.0>}
** exception error: {error,retries_exceeded,
                           {network_failure,"smtp.gmail.com",{error,timeout}}}

im able to ping "smtp.gmail.com" successfuly. not sure why the exception.. request help

**Comment by mworrell** [comment]
By 'ping' do you mean telnet to smtp.gmail.com on port 25?
If you test from your home then often the internet provider blocks outgoing port 25.
In that case you need an alternative port, gmail says on their help page:

> If you tried configuring your SMTP server on port 465 (with SSL) and port 587 (with TLS), but are still having trouble sending mail, try configuring your SMTP to use port 25 (with SSL).

**Comment by amadupu** [comment]
i tried both

ping smtp.gmail.com
PING gmail-smtp-msa.l.google.com (209.85.147.108) 56(84) bytes of data.
64 bytes from jg-in-f108.1e100.net (209.85.147.108): icmp_seq=1 ttl=39 time=288 ms
64 bytes from jg-in-f108.1e100.net (209.85.147.108): icmp_seq=2 ttl=39 time=245 ms

this show that im able to reach the smtp server from the NATed network

telnet smtp.gmail.com 25
Trying 173.194.192.108...
Trying 173.194.192.108...
just stuck there...as you hinted one possibility is port blockage by provider. 

However ive also tried specifying the ssl/tls port during {port,465} & {port, 587} & {port,25} along with {ssl, true} in the gen_smtp_client:send options.. But the issue of timout still present in all these cases.

so far im behind a NAT which likely could be causing this issue.. before i try out on a different network where NAT issues are less likely i would like to know if im missing out some thing very basic here..
