### ISSUE TITLE
new version please 🙏

### ISSUE THREAD

**Issue by dustinfarris** [gen-smtp/gen_smtp#312]
need the dropped hut dependency — can peg to the latest commit but would prefer a new release if it makes sense. thanks!

**Comment by cw789** [comment]
I also think this would be necessary with the release of Elixir v1.14 as it seems `rebar2` support is dropped in Mix.
Anyway I don't know why `hut` is build with `rebar2` within Mix.

**Comment by arjan** [comment]
@mworrell @seriyps I can release a new version tomorrow, wdyt? A lot has been changed, last release was over a year ago.. not sure if there are any backward incompatibilities though.

**Comment by mworrell** [comment]
@arjan I am for a release!  A lot has been done.

**Comment by arjan** [comment]
Okay waiting for @seriyps for feedback on #311 otherwise i'll release without it end of the day

**Comment by ak-14** [comment]
@arjan any update on this?

**Comment by arjan** [comment]
I've tagged 1.2.0 now and published to hex!

**Comment by arjan** [comment]
Docs also built and published now, and github release page updated.

**Comment by cw789** [comment]
Thanks a lot for your work.

**Comment by cw789** [comment]
One thing I've found. ExDoc `source_ref` seems to expect a tag like **v**1.2.0.
So either tag it as that or we need to manually set the `source_ref` in the rebar.config.

But this just means the source links within the docs do not work.

**Comment by arjan** [comment]
Hmm interesting.. where do you see this issue?

**Comment by cw789** [comment]
![image](https://user-images.githubusercontent.com/6823352/163145642-215e1150-5d98-49fd-ac1c-1375f181b31c.png)

**Comment by arjan** [comment]
Okay so I traced the issue, the problem is that the `rebar3_ex_doc` plugin makes this assumption, [here](https://github.com/starbelly/rebar3_ex_doc/blob/184ec396c97028a976172499d72edbff043135f6/src/rebar3_ex_doc.erl#L190)

**Comment by arjan** [comment]
was already reported actually https://github.com/starbelly/rebar3_ex_doc/issues/18
