### ISSUE TITLE
SMTP syntax errors

### ISSUE THREAD

**Issue by DerDakon** [gen-smtp/gen_smtp#93]
It's "MAIL FROM:<…>" and "RCPT TO:<…>", i.e. no spaces between colon and opening brace, see [RfC 5321](https://tools.ietf.org/html/rfc5321#page-20).

**Comment by mworrell** [comment]
True, reading the RFC it gives these examples:

```
MAIL FROM:<userx@y.foo.org>
RCPT TO:<userc@d.bar.org>
```
