### ISSUE TITLE
** exception error: no case clause matching <<0>>

### ISSUE THREAD

**Issue by nestor5** [gen-smtp/gen_smtp#94]
7> gen_smtp_client:send({"alice@outlook.com", ["bob@outlook.com"], "Subject: test\r\nFrom: Alice \r\nTo: Bob \r\n\r\nThis is the email body"}, [{relay, "smtp-mail.outlook.com"}, {username, "alice@outlook.com"}, {password, "mypassword"}, {port, 587}]).
{ok,<0.54.0>}
8>
=ERROR REPORT==== 21-Feb-2016::05:16:10 ===
Error in process <0.54.0> with exit value:
{{case_clause,<<0>>},
 [{gen_smtp_client,read_possible_multiline_reply,1,
                   [{file,"src/gen_smtp_client.erl"},{line,545}]},
  {gen_smtp_client,try_MAIL_FROM,3,
                   [{file,"src/gen_smtp_client.erl"},{line,222}]},
  {gen_smtp_client,try_sending_it,3,
                   [{file,"src/gen_smtp_client.erl"},{line,212}]},
  {gen_smtp_client,do_smtp_session,3,
                   [{file,"src/gen_smtp_client.erl"},{line,205}]},
  {gen_smtp_client,try_smtp_sessions,4,
                   [{file,"src/gen_smtp_client.erl"},{line,142}]},
  {gen_smtp_client,send_it_nonblock,3,
                   [{file,"src/gen_smtp_client.erl"},{line,109}]}]}
*\* exception error: no case clause matching <<0>>
     in function  gen_smtp_client:read_possible_multiline_reply/1 (src/gen_smtp_client.erl, line 545)
     in call from gen_smtp_client:try_MAIL_FROM/3 (src/gen_smtp_client.erl, line 222)
     in call from gen_smtp_client:try_sending_it/3 (src/gen_smtp_client.erl, line 212)
     in call from gen_smtp_client:do_smtp_session/3 (src/gen_smtp_client.erl, line 205)
     in call from gen_smtp_client:try_smtp_sessions/4 (src/gen_smtp_client.erl, line 142)
     in call from gen_smtp_client:send_it_nonblock/3 (src/gen_smtp_client.erl, line 109)

Any idea?

**Comment by seriyps** [comment]
Yoy may try to add `io:format("~p~n", [Packet])` into line https://github.com/Vagabond/gen_smtp/blob/master/src/gen_smtp_client.erl#L545 recompile and repeat your attempt to see what outlook returns before this exception happens.

**Comment by gularg** [comment]
I added the line and tried again:

2> gen_smtp_client:send({"alice@outlook.com", ["bob@outlook.com"], "Subject: test\r\nFrom: Alice \r\nTo: Bob \r\n\r\nThis is the email body"}, [{relay, "smtp-mail.outlook.com"}, {username, "alice@outlook.com"}, {password, "mypassword"}, {port, 587}]).
{ok,<0.54.0>}
3>
<<"220 BLU436-SMTP151.smtp.hotmail.com Microsoft ESMTP MAIL Service, Version: 8.0.9200.16384 ready at  Tue, 1 Mar 2016 02:30:38 -0800 \r\n">>
<<"250-BLU436-SMTP151.smtp.hotmail.com Hello [59.56.103.35]\r\n">>
<<"220 2.0.0 SMTP server ready\r\n">>
<<0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0>>
** exception error: no case clause matching <<0>>
     in function  gen_smtp_client:read_possible_multiline_reply/1 (src/gen_smtp_client.erl, line 546)
     in call from gen_smtp_client:try_MAIL_FROM/3 (src/gen_smtp_client.erl, line 222)
     in call from gen_smtp_client:try_sending_it/3 (src/gen_smtp_client.erl, line 212)
     in call from gen_smtp_client:do_smtp_session/3 (src/gen_smtp_client.erl, line 205)
     in call from gen_smtp_client:try_smtp_sessions/4 (src/gen_smtp_client.erl, line 142)
     in call from gen_smtp_client:send_it_nonblock/3 (src/gen_smtp_client.erl, line 109)
3>
=ERROR REPORT==== 1-Mar-2016::18:30:40 ===
Error in process <0.40.0> with exit value:
{{case_clause,<<0>>},
 [{gen_smtp_client,read_possible_multiline_reply,1,
                   [{file,"src/gen_smtp_client.erl"},{line,546}]},
  {gen_smtp_client,try_MAIL_FROM,3,
                   [{file,"src/gen_smtp_client.erl"},{line,222}]},
  {gen_smtp_client,try_sending_it,3,
                   [{file,"src/gen_smtp_client.erl"},{line,212}]},
  {gen_smtp_client,do_smtp_session,3,
                   [{file,"src/gen_smtp_client.erl"},{line,205}]},
  {gen_smtp_client,try_smtp_sessions,4,
                   [{file,"src/gen_smtp_client.erl"},{line,142}]},
  {gen_smtp_client,send_it_nonblock,3,
                   [{file,"src/gen_smtp_client.erl"},{line,109}]}]}

**Comment by seriyps** [comment]
wow... Sorry, have no idea.

**Comment by mworrell** [comment]
That is a weird error.

We are regularly sending email to outlook and never encountered it.

Closing for now, please re-open if the problem returns.
